spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    board:
      hostname: localhost
      username: root      #보통 직접 value 값을 할당하지 않고, KMS를 활용해서 build 하는 등의 방식으로 설정
      password: moon9494  #보통 직접 value 값을 할당하지 않고, KMS를 활용해서 build 하는 등의 방식으로 설정